# Generated by Django 4.2.7 on 2023-12-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchstock_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchstock_sku', models.PositiveIntegerField(unique=True)),
                ('part_description', models.CharField(max_length=50)),
                ('part_color', models.CharField(choices=[('White', 'White'), ('Creme', 'Creme'), ('Off-White', 'Off-White'), ('Light-Gray', 'Light-Gray'), ('Gray', 'Gray'), ('Dark-Gray', 'Dark-Gray'), ('Black', 'Black'), ('Chrome', 'Chrome'), ('Transparent', 'Transparent'), ('Brown', 'Brown'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple')], default='No Color selected', max_length=25)),
                ('part_image', models.ImageField(upload_to='')),
                ('discontinued', models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(max_length=80, unique=True)),
                ('dc_number', models.PositiveSmallIntegerField(unique=True)),
                ('rack_amount', models.SmallIntegerField()),
                ('shelf_per_rack', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_categories', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_categories', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_id', models.CharField(max_length=4)),
                ('vendor_code', models.PositiveSmallIntegerField(unique=True)),
                ('sends_parts', models.BooleanField(default=True)),
                ('available_parts', models.CharField(max_length=500)),
                ('unavailable_parts', models.CharField(max_length=500)),
                ('part_shipping', models.CharField(max_length=400)),
                ('other_part_info', models.CharField(max_length=400)),
                ('other_vendor_info', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Benchstock_part_in_DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.PositiveSmallIntegerField()),
                ('shelf_number', models.PositiveSmallIntegerField()),
                ('self_side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('benchstock_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.benchstock_part')),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.dc')),
            ],
        ),
        migrations.AddField(
            model_name='benchstock_part',
            name='furniture_type',
            field=models.ManyToManyField(to='crud_app.furniture'),
        ),
        migrations.AddField(
            model_name='benchstock_part',
            name='part_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.parts'),
        ),
        migrations.AddField(
            model_name='benchstock_part',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.vendors'),
        ),
    ]
