# Generated by Django 4.2.7 on 2023-12-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_vendors_other_part_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furniture_categories',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='part_categories',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
