# Generated by Django 4.2.7 on 2023-12-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0004_alter_benchstock_part_benchstock_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchstock_part_in_dc',
            name='optimal_quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benchstock_part_in_dc',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benchstock_part',
            name='part_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
