# Generated by Django 4.2.7 on 2023-12-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud_app', '0005_benchstock_part_in_dc_optimal_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_dc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud_app.dc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
