# Generated by Django 4.2.7 on 2023-12-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0006_userdc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDC',
        ),
    ]
