# Generated by Django 4.2.7 on 2023-12-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0008_colors_alter_benchstock_part_part_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
