# Generated by Django 4.2.7 on 2023-12-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0009_rename_colors_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchstock_part',
            name='discontinued',
            field=models.CharField(choices=[('Active', 'Active'), ('Discontinued', 'Discontinued')], default='Active', max_length=30),
        ),
    ]
