# Generated by Django 4.2.7 on 2023-12-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0010_alter_benchstock_part_discontinued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchstock_part',
            name='part_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
