# Generated by Django 4.2.7 on 2023-12-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0011_alter_benchstock_part_part_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchstock_part_in_dc',
            old_name='self_side',
            new_name='shelf_side',
        ),
    ]
