# Generated by Django 4.2.7 on 2023-12-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0013_alter_benchstock_part_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='available_parts',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='part_shipping',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='unavailable_parts',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
