# Generated by Django 4.2.7 on 2023-12-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0014_alter_vendors_available_parts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='other_vendor_info',
        ),
    ]
