# Generated by Django 4.2.7 on 2024-01-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0019_alter_slatinformation_center_slat_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slatinformation',
            name='notes',
        ),
    ]
