# Generated by Django 4.2.7 on 2024-01-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0021_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('transfer_number', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('shipping_date', models.DateField(auto_now_add=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('benchstock_part_in_dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud_app.benchstock_part_in_dc')),
                ('to_dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_dc', to='crud_app.dc')),
            ],
        ),
    ]
