# Generated by Django 4.2.7 on 2024-01-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0022_inventorytransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransfer',
            name='status',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Shipped', 'Shipped'), ('Received', 'Received')], default='Shipped', max_length=30),
        ),
    ]
