# Generated by Django 4.2.7 on 2024-01-18 14:23

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0025_alter_inventorytransfer_to_dc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchstock_part',
            name='part_image',
            field=models.ImageField(null=True, storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to=''),
        ),
    ]
